## Native MorphOS/MUI user interface
if UI_MORPHOS

fuse_SOURCES += $(ui_morphos_files)

endif

ui_morphos_files = \
                   ui/morphos/morphosdisplay.c \
                   ui/morphos/morphosdebug.h \
                   ui/morphos/morphoskeyboard.c \
                   ui/morphos/morphoskeyboard.h \
                   ui/morphos/locale.c \
                   ui/morphos/locale.h \
                   ui/morphos/Fuse_strings.h \
                   ui/morphos/morphosjoystick.c \
                   ui/morphos/morphosjoystick.h \
                   ui/morphos/morphosvideo.c \
                   ui/morphos/morphosvideo.h \
                   ui/morphos/morphosui.c \
                   ui/morphos/morphosui.h

EXTRA_DIST += \
              ui/morphos/Fuse.cd \
              ui/morphos/catalogs/polski/Fuse.ct \
              ui/morphos/catalogs/polski/ENCODING.txt
