#include "config.h"

#include "registry.h"

#include "internals.h"

#define TEST_ENTRY( x, description ) { x, #x, description, 0 }

test_description tests[] = {
  TEST_ENTRY( tape_with_unknown_block, "Tape with unknown block" ),
  TEST_ENTRY( tzx_turbo_data_with_zero_pilot_pulses_and_zero_data,
              "TZX turbo data with zero pilot pulses and zero data" ),
  TEST_ENTRY( tzx_pure_data_with_zero_used_bits,
              "TZX pure data with zero used bits" ),
  TEST_ENTRY( writing_empty_tap_file, "Writing empty .tap file" ),
  TEST_ENTRY( invalid_compressed_file_1, "Invalid compressed file 1" ),
  TEST_ENTRY( invalid_compressed_file_2, "Invalid compressed file 2" ),
  TEST_ENTRY( pointer_wraparound_in_szx_file,
              "Pointer wraparound in SZX file" ),
  TEST_ENTRY( invalid_tzx_gdb, "Invalid TZX GDB" ),
  TEST_ENTRY( empty_tzx_drb, "Empty TZX DRB" ),
  TEST_ENTRY( invalid_tzx_archive_info_block,
              "Invalid TZX archive info block" ),
  TEST_ENTRY( invalid_hardware_info_block_causes_memory_leak,
              "Invalid hardware info block causes memory leak" ),
  TEST_ENTRY( invalid_warajevo_tape_file, "Invalid Warajevo tape file" ),
  TEST_ENTRY( invalid_tzx_custom_info_block_causes_memory_leak,
              "Invalid TZX custom info block causes memory leak" ),
  TEST_ENTRY( tzx_loop_end_block_with_loop_start_block,
              "TZX loop end block with loop start block" ),
  TEST_ENTRY( tzx_loop_blocks, "TZX loop blocks" ),
  TEST_ENTRY( complete_tzx_file, "Complete TZX file" ),
  TEST_ENTRY( tzx_loop_blocks_2, "TZX loop blocks 2" ),
  TEST_ENTRY( tzx_jump_blocks, "TZX jump blocks" ),
  TEST_ENTRY( csw_empty_file, "CSW empty file" ),
  TEST_ENTRY( complete_tzx_to_tap_conversion,
              "Complete TZX to TAP conversion" ),
  TEST_ENTRY( sna_file_with_sp_0x4000, "SNA file with SP < 0x4000" ),
  TEST_ENTRY( sna_file_with_sp_0xffff, "SNA file with SP = 0xffff" ),
  TEST_ENTRY( mdr_write_protection_1, "MDR write protection 1" ),
  TEST_ENTRY( mdr_write_protection_2, "MDR write protection 2" ),
  TEST_ENTRY( complete_tzx_timings, "Complete TZX timings" ),
  TEST_ENTRY( writing_sna_file, "Writing SNA file" ),
  TEST_ENTRY( writing_plus_3_z80_file, "Writing +3 .Z80 file" ),
  TEST_ENTRY( reading_old_szx_file, "Reading old SZX file" ),
  TEST_ENTRY( rzx_invalid_frame_data_error_does_not_free_repeat_frame_pointer,
              "RZX frame data error does not free repeat-frame pointer" ),
  TEST_ENTRY( zero_tail_length_pzx_file, "Zero tail length PZX file" ),
  TEST_ENTRY( no_pilot_pulse_gdb_tzx_file, "No pilot pulse GDB TZX file" ),
  TEST_ENTRY( csw_conversion, "CSW conversion" ),
  TEST_ENTRY( csw_rle_pulse_conversion, "CSW RLE pulse conversion" ),
  TEST_ENTRY( write_szx_z80r_chunk, "Write SZX Z80R chunk" ),
  TEST_ENTRY( write_szx_spcr_chunk, "Write SZX SPCR chunk" ),
  TEST_ENTRY( write_szx_joy_chunk, "Write SZX JOY chunk" ),
  TEST_ENTRY( write_szx_keyb_chunk, "Write SZX KEYB chunk" ),
  TEST_ENTRY( write_szx_zxpr_chunk, "Write SZX ZXPR chunk" ),
  TEST_ENTRY( write_szx_ay_chunk, "Write SZX AY chunk" ),
  TEST_ENTRY( write_szx_scld_chunk, "Write SZX SCLD chunk" ),
  TEST_ENTRY( write_szx_zxat_chunk, "Write SZX ZXAT chunk" ),
  TEST_ENTRY( write_szx_zxcf_chunk, "Write SZX ZXCF chunk" ),
  TEST_ENTRY( write_szx_amxm_chunk, "Write SZX AMXM chunk" ),
  TEST_ENTRY( write_szx_side_chunk, "Write SZX SIDE chunk" ),
  TEST_ENTRY( write_szx_drum_chunk, "Write SZX DRUM chunk" ),
  TEST_ENTRY( write_szx_covx_chunk, "Write SZX COVX chunk" ),
  TEST_ENTRY( read_szx_z80r_chunk, "Read SZX Z80R chunk" ),
  TEST_ENTRY( read_szx_spcr_chunk, "Read SZX SPCR chunk" ),
  TEST_ENTRY( read_szx_joy_chunk, "Read SZX JOY chunk" ),
  TEST_ENTRY( read_szx_keyb_chunk, "Read SZX KEYB chunk" ),
  TEST_ENTRY( read_szx_zxpr_chunk, "Read SZX ZXPR chunk" ),
  TEST_ENTRY( read_szx_ay_chunk, "Read SZX AY chunk" ),
  TEST_ENTRY( read_szx_scld_chunk, "Read SZX SCLD chunk" ),
  TEST_ENTRY( read_szx_zxat_chunk, "Read SZX ZXAT chunk" ),
  TEST_ENTRY( read_szx_zxcf_chunk, "Read SZX ZXCF chunk" ),
  TEST_ENTRY( read_szx_amxm_chunk, "Read SZX AMXM chunk" ),
  TEST_ENTRY( read_szx_side_chunk, "Read SZX SIDE chunk" ),
  TEST_ENTRY( read_szx_drum_chunk, "Read SZX DRUM chunk" ),
  TEST_ENTRY( read_szx_covx_chunk, "Read SZX COVX chunk" ),
  TEST_ENTRY( write_szx_zmmc_chunk, "Write SZX ZMMC chunk" ),
  TEST_ENTRY( read_szx_zmmc_chunk, "Read SZX ZMMC chunk" ),
  TEST_ENTRY( write_szx_uspe_chunk, "Write SZX USPE chunk" ),
  TEST_ENTRY( read_szx_uspe_chunk, "Read SZX USPE chunk" ),
  TEST_ENTRY( write_szx_pltt_chunk, "Write SZX PLTT chunk" ),
  TEST_ENTRY( read_szx_pltt_chunk, "Read SZX PLTT chunk" ),
  TEST_ENTRY( write_szx_ramp_chunk, "Write SZX RAMP chunk" ),
  TEST_ENTRY( read_szx_ramp_chunk, "Read SZX RAMP chunk" ),
  TEST_ENTRY( write_szx_atrp_chunk, "Write SZX ATRP chunk" ),
  TEST_ENTRY( write_szx_cfrp_chunk, "Write SZX CFRP chunk" ),
  TEST_ENTRY( read_szx_atrp_chunk, "Read SZX ATRP chunk" ),
  TEST_ENTRY( read_szx_cfrp_chunk, "Read SZX CFRP chunk" ),
  TEST_ENTRY( write_uncompressed_szx_ramp_chunk, "Write uncompressed SZX RAMP chunk" ),
  TEST_ENTRY( write_uncompressed_szx_atrp_chunk, "Write uncompressed SZX ATRP chunk" ),
  TEST_ENTRY( write_uncompressed_szx_cfrp_chunk, "Write uncompressed SZX CFRP chunk" ),
  TEST_ENTRY( read_uncompressed_szx_ramp_chunk, "Read uncompressed SZX RAMP chunk" ),
  TEST_ENTRY( read_uncompressed_szx_atrp_chunk, "Read uncompressed SZX ATRP chunk" ),
  TEST_ENTRY( read_uncompressed_szx_cfrp_chunk, "Read uncompressed SZX CFRP chunk" ),
  TEST_ENTRY( write_szx_b128_chunk, "Write SZX B128 chunk" ),
  TEST_ENTRY( read_szx_b128_chunk, "Read SZX B128 chunk" ),
  TEST_ENTRY( write_szx_snet_chunk, "Write SZX SNET chunk" ),
  TEST_ENTRY( read_szx_snet_chunk, "Read SZX SNET chunk" ),
  TEST_ENTRY( write_szx_mfce_chunk, "Write SZX MFCE chunk" ),
  TEST_ENTRY( read_szx_mfce_chunk, "Read SZX MFCE chunk" ),
  TEST_ENTRY( write_szx_dide_chunk, "Write SZX DIDE chunk (DivIDE EPROM)" ),
  TEST_ENTRY( read_szx_dide_chunk, "Read SZX DIDE chunk (DivIDE EPROM)" ),
  TEST_ENTRY( write_szx_dmmc_chunk, "Write SZX DMMC chunk (DivMMC EPROM)" ),
  TEST_ENTRY( read_szx_dmmc_chunk, "Read SZX DMMC chunk (DivMMC EPROM)" ),
  TEST_ENTRY( write_szx_opus_chunk, "Write SZX OPUS chunk" ),
  TEST_ENTRY( read_szx_opus_chunk, "Read SZX OPUS chunk" ),
  TEST_ENTRY( write_szx_plsd_chunk, "Write SZX PLSD chunk" ),
  TEST_ENTRY( read_szx_plsd_chunk, "Read SZX PLSD chunk" ),
  TEST_ENTRY( write_szx_dock_chunk, "Write SZX DOCK chunk" ),
  TEST_ENTRY( read_szx_dock_chunk, "Read SZX DOCK chunk" ),
  TEST_ENTRY( write_szx_dirp_chunk, "Write SZX DIRP chunk" ),
  TEST_ENTRY( read_szx_dirp_chunk, "Read SZX DIRP chunk" ),
  TEST_ENTRY( write_szx_dmrp_chunk, "Write SZX DMRP chunk" ),
  TEST_ENTRY( read_szx_dmrp_chunk, "Read SZX DMRP chunk" ),
  TEST_ENTRY( write_szx_if2r_chunk, "Write SZX IF2R chunk" ),
  TEST_ENTRY( read_szx_if2r_chunk, "Read SZX IF2R chunk" ),
  TEST_ENTRY( write_szx_snef_chunk, "Write SZX SNEF chunk" ),
  TEST_ENTRY( read_szx_snef_chunk, "Read SZX SNEF chunk" ),
  TEST_ENTRY( write_szx_sner_chunk, "Write SZX SNER chunk" ),
  TEST_ENTRY( read_szx_sner_chunk, "Read SZX SNER chunk" ),
  TEST_ENTRY( write_rzx_with_incompressible_snap, "Write RZX with incompressible snap" ),
  TEST_ENTRY( tape_peek_next_block, "Tape peek next block" ),
  TEST_ENTRY( read_tzx_raw_block_edge_handling, "Read TZX RAW block edge handling" ),
  TEST_ENTRY( trailing_pause_block_tzx_file, "Trailing pause block TZX file" ),
  TEST_ENTRY( read_mono_wav_threshold_fixture, "Read mono WAV threshold fixture" ),
  TEST_ENTRY( read_stereo_wav_mixdown_fixture, "Read stereo WAV mixdown fixture" ),
  TEST_ENTRY( buffer_write_byte_stores_single_byte, "Buffer write_byte stores single byte" ),
  TEST_ENTRY( buffer_write_word_stores_little_endian_word, "Buffer write_word stores little-endian word" ),
  TEST_ENTRY( buffer_write_dword_stores_little_endian_dword, "Buffer write_dword stores little-endian dword" ),
  TEST_ENTRY( buffer_write_buffer_copies_src_contents_to_dest, "Buffer write_buffer copies src contents to dest" ),
  TEST_ENTRY( buffer_empty_predicates, "Buffer is_empty and is_not_empty" ),
  TEST_ENTRY( buffer_clear_resets_data_size_to_zero, "Buffer clear resets data size to zero" ),
  TEST_ENTRY( buffer_set_fills_n_bytes_with_given_value, "Buffer set fills N bytes with given value" ),
  TEST_ENTRY( buffer_append_copies_src_to_raw_byte_buffer, "Buffer append copies src to raw byte buffer" ),
  TEST_ENTRY( buffer_write_raw_stores_arbitrary_bytes, "Buffer write raw stores arbitrary bytes" ),
  TEST_ENTRY( buffer_auto_grows_beyond_initial_capacity, "Buffer auto-grows beyond initial capacity" ),
  TEST_ENTRY( buffer_null_accessors_return_safe_values, "Buffer null-pointer accessors return safe values" ),
  TEST_ENTRY( creator_alloc_free_and_program_getter_setter, "Creator alloc/free and program getter/setter" ),
  TEST_ENTRY( creator_major_and_minor_version_getter_setter, "Creator major and minor version getter/setter" ),
  TEST_ENTRY( creator_competition_code_and_custom_data_getter_setter, "Creator competition_code and custom data getter/setter" ),
  TEST_ENTRY( snap_main_z80_register_getter_setter_a_f_bc_de_hl_alternates, "Snap main Z80 register getter/setter (a, f, bc, de, hl, alternates)" ),
  TEST_ENTRY( snap_index_and_special_register_getter_setter_ix_iy_i_r_sp_pc, "Snap index and special register getter/setter (ix, iy, i, r, sp, pc)" ),
  TEST_ENTRY( snap_z80_status_getter_setter_iff1_iff2_im_tstates_halted, "Snap Z80 status getter/setter (iff1, iff2, im, tstates, halted)" ),
  TEST_ENTRY( microdrive_alloc_free_and_write_protect_getter_setter, "Microdrive alloc/free and write_protect getter/setter" ),
  TEST_ENTRY( microdrive_cartridge_len_and_data_getter_setter, "Microdrive cartridge_len and data getter/setter" ),
  TEST_ENTRY( microdrive_mdr_write_mdr_read_roundtrip, "Microdrive mdr_write/mdr_read roundtrip" ),
  TEST_ENTRY( snap_machine_type_getter_setter_and_default_value, "Snap machine type getter/setter and default value" ),
  TEST_ENTRY( snap_memptr_getter_setter, "Snap memptr getter/setter" ),
  TEST_ENTRY( snap_ula_128k_memory_port_and_ay_register_port_getter_setter, "Snap ULA, 128K memory port, and AY register port getter/setter" ),
  TEST_ENTRY( snap_custom_rom_flag_and_custom_rom_pages_getter_setter, "Snap custom_rom flag and custom_rom_pages getter/setter" ),
  TEST_ENTRY( snap_ram_pages_getter_setter, "Snap RAM pages getter/setter" ),
  TEST_ENTRY( snap_interface1_active_paged_and_drive_count_getter_setter, "Snap interface1 active, paged, and drive_count getter/setter" ),
  TEST_ENTRY( snap_divide_active_eprom_writeprotect_paged_and_control_getter_setter, "Snap DivIDE active, eprom_writeprotect, paged, and control getter/setter" ),
  TEST_ENTRY( snap_specdrum_active_flag_and_signed_dac_getter_setter, "Snap SpecDrum active flag and signed DAC getter/setter" ),
  TEST_ENTRY( snap_fuller_box_active_flag_getter_setter, "Snap Fuller Box active flag getter/setter" ),
  TEST_ENTRY( snap_multiface_active_paged_model_disabled_and_software_lockout_getter_setter, "Snap Multiface active, paged, model, disabled, and software_lockout getter/setter" ),
  TEST_ENTRY( snap_ay_registers_array_getter_setter_all_16_registers, "Snap AY registers array getter/setter (all 16 registers)" ),
  TEST_ENTRY( snap_beta_disk_active_paged_autoboot_and_drive_count_getter_setter, "Snap beta disk active, paged, autoboot, and drive_count getter/setter" ),
  TEST_ENTRY( snap_zxatasp_active_upload_and_writeprotect_getter_setter, "Snap ZXATASP active, upload, and writeprotect getter/setter" ),
  TEST_ENTRY( snap_zxatasp_port_a_b_c_and_control_getter_setter, "Snap ZXATASP port_a/b/c and control getter/setter" ),
  TEST_ENTRY( snap_zxatasp_pages_and_current_page_getter_setter, "Snap ZXATASP pages and current_page getter/setter" ),
  TEST_ENTRY( pzx_archive_info_tags_title_and_author_correctly_parsed, "PZX archive info tags (title and Author) correctly parsed" ),
  TEST_ENTRY( snap_divide_pages_count_and_divide_eprom_pointer_getter_setter, "Snap DivIDE pages count and divide_eprom pointer getter/setter" ),
  TEST_ENTRY( snap_divide_ram_page_pointer_array_getter_setter, "Snap DivIDE RAM page pointer array getter/setter" ),
  TEST_ENTRY( snap_divmmc_active_eprom_writeprotect_paged_and_control_getter_setter, "Snap DivMMC active, eprom_writeprotect, paged, and control getter/setter" ),
  TEST_ENTRY( snap_divmmc_pages_count_and_divmmc_eprom_pointer_getter_setter, "Snap DivMMC pages count and divmmc_eprom pointer getter/setter" ),
  TEST_ENTRY( snap_plus_d_active_paged_drive_count_custom_rom_and_direction_getter_setter, "Snap Plus D active, paged, drive_count, custom_rom, and direction getter/setter" ),
  TEST_ENTRY( snap_plus_d_fdc_byte_registers_control_track_sector_data_status_getter_setter, "Snap Plus D FDC byte registers (control, track, sector, data, status) getter/setter" ),
  TEST_ENTRY( snap_plus_d_rom_and_ram_single_pointer_getter_setter, "Snap Plus D ROM and RAM single-pointer getter/setter" ),
  TEST_ENTRY( snap_zxatasp_ram_page_pointer_array_getter_setter, "Snap ZXATASP RAM page pointer array getter/setter" ),
  TEST_ENTRY( snap_opus_discovery_active_paged_drive_count_custom_rom_and_direction_getter_setter, "Snap Opus Discovery active, paged, drive_count, custom_rom, and direction getter/setter" ),
  TEST_ENTRY( snap_opus_discovery_fdc_byte_registers_track_sector_data_status_via_ports_getter_setter, "Snap Opus Discovery FDC byte registers (track, sector, data, status, VIA ports) getter/setter" ),
  TEST_ENTRY( snap_opus_discovery_rom_and_ram_single_pointer_getter_setter, "Snap Opus Discovery ROM and RAM single-pointer getter/setter" ),
  TEST_ENTRY( snap_spectranet_boolean_int_flags_getter_setter, "Snap Spectranet boolean int flags getter/setter" ),
  TEST_ENTRY( snap_spectranet_page_a_b_programmable_trap_word_and_memory_pointers_getter_setter, "Snap Spectranet page_a/b, programmable_trap word, and memory pointers getter/setter" ),
  TEST_ENTRY( snap_disciple_active_paged_inhibit_button_drive_count_custom_rom_and_direction_getter_setter, "Snap DISCiPLE active, paged, inhibit_button, drive_count, custom_rom, and direction getter/setter" ),
  TEST_ENTRY( snap_disciple_fdc_byte_registers_control_track_sector_data_status_getter_setter, "Snap DISCiPLE FDC byte registers (control, track, sector, data, status) getter/setter" ),
  TEST_ENTRY( snap_disciple_rom_pointer_rom_length_and_ram_pointer_getter_setter, "Snap DISCiPLE ROM pointer, ROM length, and RAM pointer getter/setter" ),
  TEST_ENTRY( snap_usource_active_paged_custom_rom_int_flags_getter_setter, "Snap USource active, paged, custom_rom int flags getter/setter" ),
  TEST_ENTRY( snap_usource_rom_pointer_and_rom_length_getter_setter, "Snap USource ROM pointer and ROM length getter/setter" ),
  TEST_ENTRY( snap_uspeeched_active_and_paged_getter_setter, "Snap USpeeched active and paged getter/setter" ),
  TEST_ENTRY( snap_didaktik80_int_flags_and_fdc_byte_registers_getter_setter, "Snap Didaktik80 int flags and FDC byte registers getter/setter" ),
  TEST_ENTRY( snap_didaktik80_rom_pointer_rom_length_and_ram_pointer_getter_setter, "Snap Didaktik80 ROM pointer, ROM length, and RAM pointer getter/setter" ),
  TEST_ENTRY( snap_ulaplus_active_palette_enabled_current_register_palette_and_ff_register_getter_setter, "Snap ULAplus active, palette_enabled, current_register, palette, and ff_register getter/setter" ),
  TEST_ENTRY( snap_late_timings_getter_setter, "Snap late_timings getter/setter" ),
  TEST_ENTRY( snap_zx_printer_active_getter_setter, "Snap zx_printer_active getter/setter" ),
  TEST_ENTRY( snap_covox_active_and_covox_dac_getter_setter, "Snap covox_active and covox_dac getter/setter" ),
  TEST_ENTRY( snap_multiface_red_button_disabled_getter_setter, "Snap multiface_red_button_disabled getter/setter" ),
  TEST_ENTRY( snap_multiface_ram_pointer_and_multiface_ram_length_getter_setter, "Snap multiface_ram pointer and multiface_ram_length getter/setter" ),
  TEST_ENTRY( snap_zxmmc_active_getter_setter, "Snap zxmmc_active getter/setter" ),
  TEST_ENTRY( snap_ttx2000s_active_getter_setter, "Snap ttx2000s_active getter/setter" ),
  TEST_ENTRY( tape_turbo_block_pilot_length_sync1_length_sync2_length_getter_setter, "Tape TURBO block pilot_length, sync1_length, sync2_length getter/setter" ),
  TEST_ENTRY( tape_turbo_block_bit0_length_bit1_length_pilot_pulses_pause_getter_setter, "Tape TURBO block bit0_length, bit1_length, pilot_pulses, pause getter/setter" ),
  TEST_ENTRY( tape_pure_tone_block_pulse_length_and_count_getter_setter, "Tape PURE_TONE block pulse_length and count getter/setter" ),
  TEST_ENTRY( tape_pure_data_block_bit0_length_bit1_length_bits_in_last_byte_pause_getter_setter, "Tape PURE_DATA block bit0_length, bit1_length, bits_in_last_byte, pause getter/setter" ),
  TEST_ENTRY( tape_pause_block_pause_length_and_level_getter_setter, "Tape PAUSE block pause length and level getter/setter" ),
  TEST_ENTRY( tape_pulses_block_count_and_pulse_lengths_getter_setter, "Tape PULSES block count and pulse_lengths getter/setter" ),
  TEST_ENTRY( tape_pulse_sequence_block_count_pulse_lengths_and_pulse_repeats_getter_setter, "Tape PULSE_SEQUENCE block count, pulse_lengths, and pulse_repeats getter/setter" ),
  TEST_ENTRY( tape_raw_data_block_bit_length_bits_in_last_byte_data_data_length_and_pause_getter_setter, "Tape RAW_DATA block bit_length, bits_in_last_byte, data, data_length, and pause getter/setter" ),
  TEST_ENTRY( tape_data_block_count_tail_length_level_data_and_bit_pulses_getter_setter, "Tape DATA_BLOCK count, tail_length, level, data, and bit0/bit1 pulses getter/setter" ),
  TEST_ENTRY( tape_group_start_block_text_getter_setter, "Tape GROUP_START block text getter/setter" ),
  TEST_ENTRY( tape_loop_start_block_count_getter_setter, "Tape LOOP_START block count getter/setter" ),
  TEST_ENTRY( tape_set_signal_level_block_level_getter_setter, "Tape SET_SIGNAL_LEVEL block level getter/setter" ),
  TEST_ENTRY( rzx_alloc_and_free_lifecycle, "RZX alloc and free lifecycle" ),
  TEST_ENTRY( rzx_start_input_stop_input_and_tstates_accessor, "RZX start_input, stop_input, and tstates accessor" ),
  TEST_ENTRY( rzx_store_frame_and_iterator_get_frames_count, "RZX store_frame and iterator_get_frames count" ),
  TEST_ENTRY( rzx_store_frame_repeat_frame_detection, "RZX store_frame repeat frame detection" ),
  TEST_ENTRY( rzx_add_snap_inserts_snapshot_block, "RZX add_snap inserts snapshot block" ),
  TEST_ENTRY( rzx_iterator_begin_next_last_with_snap_and_input_blocks, "RZX iterator begin/next/last with snap and input blocks" ),
  TEST_ENTRY( rzx_get_keyid_returns_zero_with_no_signature_block, "RZX get_keyid returns zero with no signature block" ),
  TEST_ENTRY( rzx_iterator_get_frames_returns_size_t_max_for_non_input_block, "RZX iterator_get_frames returns SIZE_MAX for non-input block" ),
  TEST_ENTRY( rzx_read_uncompressed_input_respects_declared_block_length,
              "RZX uncompressed input respects declared block length" ),
  TEST_ENTRY( rzx_read_input_rejects_block_length_less_than_18,
              "RZX input rejects block length less than 18" ),
  TEST_ENTRY( rzx_iterator_delete_removes_block_from_list,
              "RZX iterator_delete removes a block from the list" ),
  TEST_ENTRY( rzx_rollback_returns_last_snap_and_removes_trailing_blocks,
              "RZX rollback returns last snap and removes trailing blocks" ),
  TEST_ENTRY( rzx_rollback_on_rzx_with_no_snap_returns_error,
              "RZX rollback on RZX with no snapshot returns CORRUPT error" ),
  TEST_ENTRY( rzx_rollback_to_returns_nth_snap,
              "RZX rollback_to(0) leaves only the first snapshot block" ),
  TEST_ENTRY( rzx_start_playback_returns_invalid_with_no_input_block,
              "RZX start_playback returns INVALID when no input block exists" ),
  TEST_ENTRY( rzx_playback_delivers_stored_in_bytes,
              "RZX playback delivers stored IN bytes and finishes after last frame" ),
  TEST_ENTRY( rzx_playback_frame_returns_corrupt_on_in_count_mismatch,
              "RZX playback_frame returns CORRUPT on IN count mismatch" ),
  TEST_ENTRY( snap_kempston_mouse_active_getter_setter, "Snap kempston_mouse_active getter/setter" ),
  TEST_ENTRY( snap_interface1_custom_rom_rom_pointer_and_rom_length_getter_setter, "Snap interface1 custom_rom flag, ROM pointer, and ROM length getter/setter" ),
  TEST_ENTRY( snap_melodik_active_getter_setter, "Snap melodik_active getter/setter" ),
  TEST_ENTRY( snap_simpleide_active_getter_setter, "Snap simpleide_active getter/setter" ),
  TEST_ENTRY( snap_issue2_getter_setter, "Snap issue2 keyboard mode getter/setter" ),
  TEST_ENTRY( snap_interface2_active_and_rom_getter_setter, "Snap interface2_active flag and interface2_rom pointer getter/setter" ),
  TEST_ENTRY( snap_joystick_active_count_list_and_inputs_getter_setter, "Snap joystick_active_count, joystick_list, and joystick_inputs getter/setter" ),
  TEST_ENTRY( tape_rom_block_data_data_length_and_pause_getter_setter, "Tape ROM block data, data_length, and pause getter/setter" ),
  TEST_ENTRY( tzx_pulse_sequence_over_255_splits_into_multiple_pulses_blocks, "TZX PULSE_SEQUENCE over 255 pulses splits into multiple PULSES blocks" ),
  TEST_ENTRY( machine_capabilities_16k_and_48k_have_no_capabilities, "Machine capabilities: 16K and 48K have a beeper; UNKNOWN has no capabilities" ),
  TEST_ENTRY( machine_capabilities_48k_ntsc_has_ntsc_only, "Machine capabilities: 48K NTSC has NTSC and a beeper" ),
  TEST_ENTRY( machine_capabilities_tc2048_has_timex_and_kempston, "Machine capabilities: TC2048 has Timex memory/video, Kempston joystick, and a beeper" ),
  TEST_ENTRY( machine_capabilities_tc2068_has_ay_timex_and_dock, "Machine capabilities: TC2068 has AY, Timex memory/video, dock, and a beeper" ),
  TEST_ENTRY( machine_capabilities_ts2068_has_ay_timex_dock_and_ntsc, "Machine capabilities: TS2068 has AY, Timex memory/video, dock, NTSC, and a beeper" ),
  TEST_ENTRY( machine_capabilities_128k_has_ay_and_128_memory, "Machine capabilities: 128K has AY and 128-style memory" ),
  TEST_ENTRY( machine_capabilities_plus2_has_ay_128_memory_and_sinclair_joystick, "Machine capabilities: +2 has AY, 128 memory, and Sinclair joystick" ),
  TEST_ENTRY( machine_capabilities_plus2a_has_ay_128_plus3_memory_and_sinclair_joystick, "Machine capabilities: +2A has AY, 128/+3 memory, and Sinclair joystick" ),
  TEST_ENTRY( machine_capabilities_plus3_and_plus3e_have_full_plus3_capabilities, "Machine capabilities: +3 and +3e have full +3 capability set" ),
  TEST_ENTRY( machine_capabilities_128e_has_ay_128_plus3_memory_and_sinclair_joystick, "Machine capabilities: 128Ke has AY, 128/+3 memory, and Sinclair joystick" ),
  TEST_ENTRY( machine_capabilities_pent_has_ay_128_memory_and_trdos, "Machine capabilities: Pentagon 128K has AY, 128 memory, and TRDOS disk" ),
  TEST_ENTRY( machine_capabilities_pent512_has_ay_128_trdos_and_pent512_memory, "Machine capabilities: Pentagon 512K has AY, 128 memory, TRDOS, and Pentagon 512 memory" ),
  TEST_ENTRY( machine_capabilities_pent1024_has_ay_128_trdos_pent512_and_pent1024_memory, "Machine capabilities: Pentagon 1024K has all Pentagon capabilities" ),
  TEST_ENTRY( machine_capabilities_scorp_has_ay_128_trdos_scorp_memory_and_even_m1, "Machine capabilities: Scorpion has AY, 128 memory, TRDOS, Scorpion memory, and even-M1" ),
  TEST_ENTRY( machine_capabilities_se_has_ay_128_memory_timex_video_kempston_and_se_memory, "Machine capabilities: SE has AY, 128 memory, Timex video, Kempston joystick, SE memory, and a beeper" ),
  TEST_ENTRY( machine_name_returns_correct_string_for_all_machines, "libspectrum_machine_name returns correct string for every machine type" ),
  TEST_ENTRY( joystick_name_returns_correct_string_for_all_types, "libspectrum_joystick_name returns correct string for every joystick type" ),
  TEST_ENTRY( snap_beta_disk_custom_rom_direction_and_fdc_byte_registers_getter_setter, "Snap BetaDisk custom_rom, direction, and FDC byte registers getter/setter" ),
  TEST_ENTRY( snap_beta_disk_rom_single_pointer_getter_setter, "Snap BetaDisk ROM single-pointer getter/setter" ),
  TEST_ENTRY( snap_divmmc_ram_page_pointer_array_getter_setter, "Snap DivMMC RAM page pointer array getter/setter" ),
  TEST_ENTRY( snap_tc2068_dock_exrom_active_cart_pointer_and_ram_flag_getter_setter, "Snap TC2068 DOCK/EXROM active, cart pointer, and ram flag getter/setter" ),
  TEST_ENTRY( tape_comment_block_text_getter_setter, "Tape COMMENT block text getter/setter" ),
  TEST_ENTRY( tape_message_block_text_and_pause_getter_setter, "Tape MESSAGE block text and pause getter/setter" ),
  TEST_ENTRY( tape_archive_info_block_count_ids_and_texts_getter_setter, "Tape ARCHIVE_INFO block count, ids, and texts getter/setter" ),
  TEST_ENTRY( tape_hardware_block_count_types_ids_and_values_getter_setter, "Tape HARDWARE block count, types, ids, and values getter/setter" ),
  TEST_ENTRY( tape_select_block_count_offsets_and_texts_getter_setter, "Tape SELECT block count, offsets, and texts getter/setter" ),
  TEST_ENTRY( tape_custom_block_text_data_and_data_length_getter_setter, "Tape CUSTOM block text, data, and data_length getter/setter" ),
  TEST_ENTRY( tape_jump_block_offset_getter_setter, "Tape JUMP block offset getter/setter" ),
  TEST_ENTRY( tape_block_description_returns_correct_string_for_all_types, "Tape block description returns correct string for all 25 block types" ),
  TEST_ENTRY( tape_pause_tstates_getter_setter_across_block_types, "Tape pause_tstates getter/setter across PAUSE, ROM, TURBO, PURE_DATA, RAW_DATA, and MESSAGE block types" ),
  TEST_ENTRY( tape_rle_pulse_block_scale_data_and_data_length_getter_setter, "Tape RLE_PULSE block scale, data, and data_length getter/setter" ),
  TEST_ENTRY( snap_custom_roms_pointer_array_and_rom_length_getter_setter, "Snap custom roms[] pointer array and rom_length[] getter/setter" ),
  TEST_ENTRY( snap_slt_level_data_length_screen_and_screen_level_getter_setter, "Snap slt[] level data, slt_length[], slt_screen, and slt_screen_level getter/setter" ),
  TEST_ENTRY( snap_multiface_model_3_getter_setter, "Snap multiface_model_3 getter/setter" ),
  TEST_ENTRY( snap_last_instruction_ei_and_set_f_getter_setter, "Snap last_instruction_ei and last_instruction_set_f getter/setter" ),
  TEST_ENTRY( snap_out_plus3_memoryport_and_scld_hsr_dec_getter_setter, "Snap out_plus3_memoryport, out_scld_hsr, and out_scld_dec getter/setter" ),
  TEST_ENTRY( snap_zxcf_active_upload_memctl_and_pages_getter_setter, "Snap ZXCF active, upload, memctl, and pages getter/setter" ),
  TEST_ENTRY( snap_zxcf_ram_page_pointer_array_getter_setter, "Snap ZXCF RAM page pointer array getter/setter" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_null_source_is_invalid, "libspectrum_zx_string_to_utf8: NULL src is invalid" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_plain_ascii, "libspectrum_zx_string_to_utf8: plain ASCII passed through unchanged" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_trailing_spaces_stripped, "libspectrum_zx_string_to_utf8: trailing spaces stripped" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_special_chars, "libspectrum_zx_string_to_utf8: special chars convert to Unicode equivalents" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_udg_char, "libspectrum_zx_string_to_utf8: UDG char 0x90 renders as \\a" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_spectrum_token, "libspectrum_zx_string_to_utf8: 128K and standard Spectrum tokens render correctly" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_buffer_too_short_is_invalid, "libspectrum_zx_string_to_utf8: short buffer is invalid" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_graphics_token, "libspectrum_zx_string_to_utf8: graphics tokens render as Unicode block elements" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_control_char, "libspectrum_zx_string_to_utf8: control character 0x01 renders as ?" ),
  TEST_ENTRY( utilities_zx_string_to_utf8_empty_source, "libspectrum_zx_string_to_utf8: empty source produces empty output" ),
  TEST_ENTRY( write_szx_if1_chunk, "Write SZX IF1 chunk (Interface 1 without custom ROM)" ),
  TEST_ENTRY( read_szx_if1_chunk, "Read SZX IF1 chunk (Interface 1 without custom ROM)" ),
  TEST_ENTRY( timings_48k_processor_speed_and_frame_timing, "Timings: 48K processor speed and frame timing" ),
  TEST_ENTRY( timings_128k_processor_speed_and_frame_timing, "Timings: 128K processor speed and frame timing" ),
  TEST_ENTRY( timings_pentagon_processor_speed_and_frame_timing, "Timings: Pentagon processor speed and frame timing" ),
  TEST_ENTRY( timings_ts2068_processor_speed_and_frame_timing, "Timings: TS2068 processor speed and frame timing" ),
  TEST_ENTRY( timings_plus3_processor_speed_and_frame_timing, "Timings: +3 processor speed and frame timing (Amstrad ASIC)" ),
  TEST_ENTRY( timings_tc2048_processor_speed_and_frame_timing, "Timings: TC2048 processor speed and frame timing (Timex SCLD 50 Hz)" ),
  TEST_ENTRY( timings_scorpion_processor_speed_and_frame_timing, "Timings: Scorpion processor speed and frame timing" ),
  TEST_ENTRY( timings_unknown_machine_returns_zero_for_all_frame_timings, "Timings: UNKNOWN machine returns zero for all frame timings" ),
  TEST_ENTRY( timings_48k_frame_timing_accessors, "Timings: 48K frame timing accessors (left_border, horizontal_screen, right_border, horizontal_retrace, top_border, vertical_screen, bottom_border, vertical_retrace, top_left_pixel)" ),
  TEST_ENTRY( timings_unknown_machine_frame_accessors_return_zero, "Timings: UNKNOWN machine frame timing accessors all return zero" ),
  TEST_ENTRY( tape_present_returns_false_for_empty_tape, "libspectrum_tape_present returns 0 for empty tape" ),
  TEST_ENTRY( tape_present_true_after_load_and_false_after_clear, "libspectrum_tape_present/tape_clear: present after load, absent after clear" ),
  TEST_ENTRY( tape_iterator_init_on_empty_tape_returns_null, "Tape iterator: init on empty tape returns NULL" ),
  TEST_ENTRY( tape_iterator_traverses_appended_blocks_in_order, "Tape iterator: traverses appended blocks in order" ),
  TEST_ENTRY( tape_iterator_peek_next_returns_null_at_last_block, "Tape iterator: peek_next returns NULL at last block" ),
  TEST_ENTRY( tape_iterator_peek_next_does_not_advance_iterator, "Tape iterator: peek_next does not advance iterator" ),
  TEST_ENTRY( tape_position_returns_zero_for_first_block, "Tape position: returns 0 for first block" ),
  TEST_ENTRY( tape_nth_block_selects_correct_block, "Tape nth_block: selects correct block and updates position" ),
  TEST_ENTRY( tape_insert_block_into_empty_tape_sets_current_block, "Tape insert_block: inserting into empty tape sets current_block" ),
  TEST_ENTRY( tape_insert_block_at_position, "Tape insert_block: inserts block at given position" ),
  TEST_ENTRY( tape_remove_block_from_tape, "Tape remove_block: removes middle block, leaving remaining blocks in order" ),
  TEST_ENTRY( tape_peek_last_block_returns_last_appended, "Tape peek_last_block: returns the last appended block" ),
  TEST_ENTRY( tape_select_next_block_advances_and_wraps, "Tape select_next_block: advances current block and wraps at end" ),
  TEST_ENTRY( tape_count_returns_correct_count, "libspectrum_tape_count: returns correct count as blocks are appended" ),
  TEST_ENTRY( tape_block_description_rom,              "libspectrum_tape_block_description: ROM block -> \"Standard Speed Data\"" ),
  TEST_ENTRY( tape_block_description_turbo,            "libspectrum_tape_block_description: Turbo block -> \"Turbo Speed Data\"" ),
  TEST_ENTRY( tape_block_description_pure_tone,        "libspectrum_tape_block_description: Pure Tone block -> \"Pure Tone\"" ),
  TEST_ENTRY( tape_block_description_pulses,           "libspectrum_tape_block_description: Pulses block -> \"List of Pulses\"" ),
  TEST_ENTRY( tape_block_description_pure_data,        "libspectrum_tape_block_description: Pure Data block -> \"Pure Data\"" ),
  TEST_ENTRY( tape_block_description_raw_data,         "libspectrum_tape_block_description: Raw Data block -> \"Raw Data\"" ),
  TEST_ENTRY( tape_block_description_generalised_data, "libspectrum_tape_block_description: Generalised Data block -> \"Generalised Data\"" ),
  TEST_ENTRY( tape_block_description_pause,            "libspectrum_tape_block_description: Pause block -> \"Pause\"" ),
  TEST_ENTRY( tape_block_description_group_start,      "libspectrum_tape_block_description: Group Start block -> \"Group Start\"" ),
  TEST_ENTRY( tape_block_description_group_end,        "libspectrum_tape_block_description: Group End block -> \"Group End\"" ),
  TEST_ENTRY( tape_block_description_jump,             "libspectrum_tape_block_description: Jump block -> \"Jump\"" ),
  TEST_ENTRY( tape_block_description_loop_start,       "libspectrum_tape_block_description: Loop Start block -> \"Loop Start Block\"" ),
  TEST_ENTRY( tape_block_description_loop_end,         "libspectrum_tape_block_description: Loop End block -> \"Loop End\"" ),
  TEST_ENTRY( tape_block_description_select,           "libspectrum_tape_block_description: Select block -> \"Select\"" ),
  TEST_ENTRY( tape_block_description_stop48,           "libspectrum_tape_block_description: Stop48 block -> \"Stop Tape If In 48K Mode\"" ),
  TEST_ENTRY( tape_block_description_set_signal_level, "libspectrum_tape_block_description: Set Signal Level block -> \"Set Signal Level\"" ),
  TEST_ENTRY( tape_block_description_comment,          "libspectrum_tape_block_description: Comment block -> \"Comment\"" ),
  TEST_ENTRY( tape_block_description_message,          "libspectrum_tape_block_description: Message block -> \"Message\"" ),
  TEST_ENTRY( tape_block_description_archive_info,     "libspectrum_tape_block_description: Archive Info block -> \"Archive Info\"" ),
  TEST_ENTRY( tape_block_description_hardware,         "libspectrum_tape_block_description: Hardware block -> \"Hardware Information\"" ),
  TEST_ENTRY( tape_block_description_custom,           "libspectrum_tape_block_description: Custom block -> \"Custom Info\"" ),
  TEST_ENTRY( tape_block_description_concat,           "libspectrum_tape_block_description: Concat block -> \"Glue Block\"" ),
  TEST_ENTRY( tape_block_description_rle_pulse,        "libspectrum_tape_block_description: RLE Pulse block -> \"RLE Pulse\"" ),
  TEST_ENTRY( tape_block_description_pulse_sequence,   "libspectrum_tape_block_description: Pulse Sequence block -> \"Pulse Sequence\"" ),
  TEST_ENTRY( tape_block_description_data_block,       "libspectrum_tape_block_description: Data Block -> \"Data Block\"" ),
  TEST_ENTRY( identify_class_unknown_returns_class_unknown, "libspectrum_identify_class: UNKNOWN maps to CLASS_UNKNOWN" ),
  TEST_ENTRY( identify_class_tape_tap_returns_class_tape, "libspectrum_identify_class: TAPE_TAP maps to CLASS_TAPE" ),
  TEST_ENTRY( identify_class_tape_tzx_returns_class_tape, "libspectrum_identify_class: TAPE_TZX maps to CLASS_TAPE" ),
  TEST_ENTRY( identify_class_tape_pzx_returns_class_tape, "libspectrum_identify_class: TAPE_PZX maps to CLASS_TAPE" ),
  TEST_ENTRY( identify_class_tape_csw_returns_class_tape, "libspectrum_identify_class: TAPE_CSW maps to CLASS_TAPE" ),
  TEST_ENTRY( identify_class_snapshot_sna_returns_class_snapshot, "libspectrum_identify_class: SNAPSHOT_SNA maps to CLASS_SNAPSHOT" ),
  TEST_ENTRY( identify_class_snapshot_szx_returns_class_snapshot, "libspectrum_identify_class: SNAPSHOT_SZX maps to CLASS_SNAPSHOT" ),
  TEST_ENTRY( identify_class_snapshot_z80_returns_class_snapshot, "libspectrum_identify_class: SNAPSHOT_Z80 maps to CLASS_SNAPSHOT" ),
  TEST_ENTRY( identify_class_recording_rzx_returns_class_recording, "libspectrum_identify_class: RECORDING_RZX maps to CLASS_RECORDING" ),
  TEST_ENTRY( identify_class_compressed_gz_returns_class_compressed, "libspectrum_identify_class: COMPRESSED_GZ maps to CLASS_COMPRESSED" ),
  TEST_ENTRY( identify_class_compressed_bz2_returns_class_compressed, "libspectrum_identify_class: COMPRESSED_BZ2 maps to CLASS_COMPRESSED" ),
  TEST_ENTRY( identify_class_disk_dsk_returns_class_disk_plus3, "libspectrum_identify_class: DISK_DSK maps to CLASS_DISK_PLUS3" ),
  TEST_ENTRY( identify_class_disk_trd_returns_class_disk_trdos, "libspectrum_identify_class: DISK_TRD maps to CLASS_DISK_TRDOS" ),
  TEST_ENTRY( identify_class_disk_mdr_returns_class_microdrive, "libspectrum_identify_class: MICRODRIVE_MDR maps to CLASS_MICRODRIVE" ),
  TEST_ENTRY( identify_class_disk_img_returns_class_disk_plusd, "libspectrum_identify_class: DISK_IMG maps to CLASS_DISK_PLUSD" ),
  TEST_ENTRY( identify_class_harddisk_hdf_returns_class_harddisk, "libspectrum_identify_class: HARDDISK_HDF maps to CLASS_HARDDISK" ),
  TEST_ENTRY( identify_class_cartridge_dck_returns_class_cartridge_timex, "libspectrum_identify_class: CARTRIDGE_DCK maps to CLASS_CARTRIDGE_TIMEX" ),
  TEST_ENTRY( identify_class_cartridge_if2_returns_class_cartridge_if2, "libspectrum_identify_class: CARTRIDGE_IF2 maps to CLASS_CARTRIDGE_IF2" ),
  TEST_ENTRY( identify_class_disk_udi_returns_class_disk_generic, "libspectrum_identify_class: DISK_UDI maps to CLASS_DISK_GENERIC" ),
  TEST_ENTRY( identify_class_pok_returns_class_auxiliary, "libspectrum_identify_class: AUX_POK maps to CLASS_AUXILIARY" ),
  TEST_ENTRY( identify_class_screen_scr_returns_class_screenshot, "libspectrum_identify_class: SCREEN_SCR maps to CLASS_SCREENSHOT" ),
  TEST_ENTRY( identify_class_disk_opd_returns_class_disk_opus, "libspectrum_identify_class: DISK_OPD maps to CLASS_DISK_OPUS" ),
  TEST_ENTRY( identify_class_disk_d80_returns_class_disk_didaktik, "libspectrum_identify_class: DISK_D80 maps to CLASS_DISK_DIDAKTIK" ),
  TEST_ENTRY( utilities_version_returns_nonempty_string, "libspectrum_version: returns non-empty string" ),
  TEST_ENTRY( utilities_check_version_current_version_returns_true, "libspectrum_check_version: current version satisfies itself" ),
  TEST_ENTRY( utilities_check_version_very_old_required_returns_true, "libspectrum_check_version: very old required version (0.0.0) is satisfied" ),
  TEST_ENTRY( utilities_check_version_future_major_returns_false, "libspectrum_check_version: future major version (99.0.0) is not satisfied" ),
  TEST_ENTRY( identify_file_tzx_magic_returns_tape_tzx, "libspectrum_identify_file: TZX magic bytes → TAPE_TZX" ),
  TEST_ENTRY( identify_file_szx_magic_returns_snapshot_szx, "libspectrum_identify_file: SZX magic bytes → SNAPSHOT_SZX" ),
  TEST_ENTRY( identify_file_rzx_magic_returns_recording_rzx, "libspectrum_identify_file: RZX magic bytes → RECORDING_RZX" ),
  TEST_ENTRY( identify_file_pzx_magic_returns_tape_pzx, "libspectrum_identify_file: PZX magic bytes → TAPE_PZX" ),
  TEST_ENTRY( identify_file_unknown_buffer_returns_unknown, "libspectrum_identify_file: unrecognised data → ID_UNKNOWN" ),
  TEST_ENTRY( identify_file_with_class_tzx_returns_type_and_tape_class, "libspectrum_identify_file_with_class: TZX → type=TAPE_TZX class=TAPE" ),
  TEST_ENTRY( identify_file_with_class_szx_returns_type_and_snapshot_class, "libspectrum_identify_file_with_class: SZX → type=SNAPSHOT_SZX class=SNAPSHOT" ),
  TEST_ENTRY( identify_file_raw_tzx_magic_returns_tape_tzx, "libspectrum_identify_file_raw: TZX magic bytes → TAPE_TZX" ),
  TEST_ENTRY( identify_file_raw_gz_magic_returns_compressed_gz, "libspectrum_identify_file_raw: GZ magic bytes → COMPRESSED_GZ (no decompression)" ),
  TEST_ENTRY( identify_file_raw_sna_filename_returns_snapshot_sna, "libspectrum_identify_file_raw: .sna filename → SNAPSHOT_SNA (extension-only match)" ),
  TEST_ENTRY( identify_file_raw_unknown_buffer_returns_unknown, "libspectrum_identify_file_raw: unrecognised data → ID_UNKNOWN" ),
  TEST_ENTRY( split_to_48k_pages_distributes_memory_to_correct_pages, "libspectrum_split_to_48k_pages: distributes each 16K region to pages 5, 2, and 0" ),
  TEST_ENTRY( split_to_48k_pages_fails_when_page_already_occupied, "libspectrum_split_to_48k_pages: returns LOGIC error when a page is already occupied" ),
  TEST_ENTRY( write_snap_page_writes_ram_data_to_buffer, "libspectrum_write_snap_page: writes RAM page data to buffer" ),
  TEST_ENTRY( write_snap_page_fills_0xff_for_absent_page, "libspectrum_write_snap_page: fills 0xff when the page pointer is NULL" ),
  TEST_ENTRY( tape_block_metadata_data_block_returns_zero, "libspectrum_tape_block_metadata: data blocks (ROM, TURBO, PURE_TONE, PAUSE, STOP48) return 0" ),
  TEST_ENTRY( tape_block_metadata_metadata_block_returns_one, "libspectrum_tape_block_metadata: metadata blocks (ARCHIVE_INFO, GROUP_START, COMMENT, HARDWARE) return 1" ),
  TEST_ENTRY( tape_block_length_pause_block_returns_pause_tstates, "libspectrum_tape_block_length: PAUSE block returns stored length_tstates" ),
  TEST_ENTRY( tape_block_length_pure_tone_returns_pulses_times_length, "libspectrum_tape_block_length: PURE_TONE block returns pulses × pulse_length" ),
  TEST_ENTRY( tape_block_length_metadata_block_returns_zero, "libspectrum_tape_block_length: GROUP_START (metadata) block returns 0" ),
  TEST_ENTRY( tape_state_returns_pilot_for_new_rom_block, "libspectrum_tape_state: returns PILOT for freshly loaded ROM block" ),
  TEST_ENTRY( tape_set_state_updates_state_of_rom_block, "libspectrum_tape_set_state: updates state of current ROM block" ),
  TEST_ENTRY( tape_current_block_returns_null_on_empty_tape, "libspectrum_tape_current_block: returns NULL for tape with no current block" ),
  TEST_ENTRY( tape_current_block_returns_first_block_after_init, "libspectrum_tape_current_block: returns first appended block after iterator_init" ),
  TEST_ENTRY( tape_block_set_type_changes_block_type, "libspectrum_tape_block_set_type: changes block type from PAUSE to PURE_TONE" ),
  TEST_ENTRY( tape_state_on_fresh_tape_returns_invalid, "libspectrum_tape_alloc/tape_free: allocation and deallocation succeeds" ),
  TEST_ENTRY( tape_set_state_and_get_state_round_trip, "libspectrum_tape_block_free: free a standalone block without tape" ),
  TEST_ENTRY( tape_block_type_returns_type_set_at_alloc, "libspectrum_tape_block_type: returns type set at alloc (PURE_TONE)" ),
  TEST_ENTRY( tape_block_alloc_several_types, "libspectrum_tape_block_alloc: allocates blocks of 8 different types with correct type" ),
};

size_t test_count = ARRAY_SIZE( tests );
